### ISSUE TITLE
Doesn't work with Firefox ?

### ISSUE THREAD

**Issue by clement-buchart** [Arthie/tailwindcssinjs#5]
Hello, 

I've been trying to use this lib in a project of mine.
You may already be aware, but it doesn't seem to be usable with Firefox : 
```
Unhandled Runtime Error

SyntaxError: invalid regexp group

Call Stack
twClassesComposer
node_modules/@tailwindcssinjs/class-composer/lib/classComposer.js (16:0)
twClassesVariantsParser
node_modules/@tailwindcssinjs/class-composer/lib/classComposer.js (58:0)
tailwindcssinjs
node_modules/@tailwindcssinjs/macro/lib/tailwindcssinjs.js (19:0)
<unknown>
webpack-internal:///./components/gui/Button.tsx (23:92)
```

It seems to be related to the following regex : 
```
  const VARIANT_ARRAY_SYNTAX_REGEX = new RegExp(
    `(?<variant>\\S+(?:\\${separator}\\w+)?)\\[(?<classes>(?:.|\\n)*?)\\]`,
    "g"
  );
```
Indeed, simply trying to instantiate this regex in Firefox cause `invalid regexp group`.
My guess is that it is because Firefox doesn't support negative look-behind.
Someone listed here information about negative look-behind support : https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent

Do you think the regex could be written differently to avoid negative look-behind ?

**Comment by Arthie** [comment]
Hey, @clement-buchart I released a new version that should make It usable in firefox! Please try again using the latest version (v0.7.2)

You are correct the problem was with that regex I removed the named capture groups and that seemed to have made it work in firefox!

Thanks for reporting this issue!

**Comment by clement-buchart** [comment]
Hello, 

Yes, v0.7.2 fixed it :+1: 

That was fast, thank you !
