### ISSUE TITLE
help with tailwindcss-data usage

### ISSUE THREAD

**Issue by brumm** [Arthie/tailwindcssinjs#6]
Hey folks,

I'm interested in building a tailwind cheatsheet which should be able to programmatically generate a list of tailwind classes given a config. I _think_ `tailwindcss-data` might be able to help me with this, but I don't quite get how it all fits together. It seems that, based on the usage inside `macro` and the `typescript`, it's not a simple procedure and requires lots of deeper postcss knowledge.

Would you be willing help me out with a concise example on how to go from `tailwindData(config, corePlugins)` to a list of generated classnames?

Thanks in advance!

**Comment by brumm** [comment]
Of course I managed to get things working after writing the issue ;)

For everyone coming after me, this node snippet will create two files, one with all (non-variant, non-screen prefixed) class names and their property/values. The other saves the resolved (read: final, generated) config based on a combination of the default config and a user-supplied custom config.

```js
const fs = require('fs')
const { default: corePlugins } = require('tailwindcss/lib/corePlugins')
const { tailwindData } = require('@tailwindcssinjs/tailwindcss-data')

const {
  transformPostcssRootToPostcssRules,
  transformPostcssRulesToTwObjectMap,
} = require('@tailwindcssinjs/transformers')

const {
  requireTailwindConfig,
} = require('@tailwindcssinjs/tailwindcss-data/lib/tailwindcssConfig')

const customConfig = {
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
}

const { componentsRoot, utilitiesRoot, resolvedConfig, ...rest } = tailwindData(
  customConfig,
  corePlugins
)

const componentRules = transformPostcssRootToPostcssRules(componentsRoot)
const utilityRules = transformPostcssRootToPostcssRules(utilitiesRoot)
const twObjectMap = transformPostcssRulesToTwObjectMap(
  utilityRules,
  componentRules
)

let rules = {}

for (const [key, value] of twObjectMap.entries()) {
  for (const node of value.root.nodes[0].nodes) {
    if (rules[key] === undefined) {
      rules[key] = []
    }

    rules[key].push({
      prop: node.prop,
      value: node.value,
    })
  }
}

fs.writeFileSync('./rules.json', JSON.stringify(rules, null, 2))
fs.writeFileSync('./config.json', JSON.stringify(resolvedConfig, null, 2))

```

**Comment by Arthie** [comment]
Glad you figured out how to make it work! The documentation is still lacking since the API isn't stable yet. I'm still working on it.

I've made some changes to tailwindcss-data here is an updated version of the script compatible with tailwindcss-data v0.9.x

```javascript
const fs = require('fs')
const { default: corePlugins } = require('tailwindcss/lib/corePlugins')
const { tailwindData, transformPostcssRootsToTwObjectMap } = require('@tailwindcssinjs/tailwindcss-data')

const customConfig = {
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
}

const { componentsRoot, utilitiesRoot, resolvedConfig, ...rest } = tailwindData(
  customConfig,
  corePlugins
)

const twObjectMap = transformPostcssRootsToTwObjectMap(
  [utilitiesRoot, componentsRoot]
)

let rules = {}

for (const [key, value] of twObjectMap.entries()) {
  for (const rule of value.nodes) {
    for (const node of rule.nodes) {
      if (rules[key] === undefined) {
        rules[key] = []
      }

      rules[key].push({
        prop: node.prop,
        value: node.value,
      })
    }
  }
}

fs.writeFileSync('./rules.json', JSON.stringify(rules, null, 2))
fs.writeFileSync('./config.json', JSON.stringify(resolvedConfig, null, 2))
```

 P.S. excuse me for the long response time I took an extended break from programming this summer!

**Comment by brumm** [comment]
Thank you for sharing the updated version!
